import {
    // NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'
import {
    APPROVAL_PREFIX_PATH,
    NETWORKS_PREFIX_PATH,
    PACKAGE_PREFIX_PATH,
    PROFILEMANAGEMENT_PREFIX_PATH,
    REPORTS_PREFIX_PATH,
    SETTINGS_PREFIX_PATH,
    SIGNUP_PREFIX_PATH,
    TOOLS_PREFIX_PATH,
} from '@/constants/route.constant'

const networksNavigation: NavigationTree[] = [
    {
        key: 'networks',
        path: `${NETWORKS_PREFIX_PATH}`,
        title: 'Networks',
        translateKey: 'nav.networks',
        icon: 'networks',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },

        subMenu: [
            {
                key: 'collapseMenu.genealogyTree',
                path: `${NETWORKS_PREFIX_PATH}/genealogy-tree`,
                title: 'Genealogy Tree',
                translateKey: 'nav.collapseMenu.genealogyTree',
                icon: 'genealogyTree',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.treeView',
                path: `${NETWORKS_PREFIX_PATH}/tree-view`,
                title: 'Tree View',
                translateKey: 'nav.collapseMenu.treeView',
                icon: 'treeView',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.downlineMembers',
                path: `${NETWORKS_PREFIX_PATH}/downline-members`,
                title: 'Downline Members',
                translateKey: 'nav.collapseMenu.downlineMembers',
                icon: 'downlineMembers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const signupNavigation: NavigationTree[] = [
    {
        key: 'signup',
        path: `${SIGNUP_PREFIX_PATH}`,
        title: 'Signup',
        translateKey: 'nav.signup',
        icon: 'signup',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },

        subMenu: [
            {
                key: 'collapseMenu.register',
                path: `${SIGNUP_PREFIX_PATH}/register`,
                title: 'Register',
                translateKey: 'nav.collapseMenu.register',
                icon: 'register',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.bulkRegister',
                path: `${SIGNUP_PREFIX_PATH}/bulk-register`,
                title: 'Bulk Register',
                translateKey: 'nav.collapseMenu.bulkRegister',
                icon: 'bulkRegister',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const approvalNavigation: NavigationTree[] = [
    {
        key: 'approval',
        path: `${APPROVAL_PREFIX_PATH}`,
        title: 'Approval',
        translateKey: 'nav.approval',
        icon: 'approval',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            {
                key: 'collapseMenu.registerationApproval',
                path: `${APPROVAL_PREFIX_PATH}/registeration-approval`,
                title: 'Registeration Approval',
                translateKey: 'nav.collapseMenu.registerationApproval',
                icon: 'registerationApproval',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const profileManagementNavigation: NavigationTree[] = [
    {
        key: 'profileManagement',
        path: `${PROFILEMANAGEMENT_PREFIX_PATH}`,
        title: 'Profile Management',
        translateKey: 'nav.profileManagement',
        icon: 'profileManagement',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            {
                key: 'collapseMenu.profileview',
                path: `${PROFILEMANAGEMENT_PREFIX_PATH}/profile-view`,
                title: 'Profile View',
                translateKey: 'nav.collapseMenu.profileview',
                icon: 'profileview',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.memberlist',
                path: `${PROFILEMANAGEMENT_PREFIX_PATH}/member-list`,
                title: 'Member list',
                translateKey: 'nav.collapseMenu.memberlist',
                icon: 'memberlist',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.KYCdetails',
                path: `${PROFILEMANAGEMENT_PREFIX_PATH}/kyc-details`,
                title: 'KYC Details',
                translateKey: 'nav.collapseMenu.KYCdetails',
                icon: 'KYCdetails',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const packageNavigation: NavigationTree[] = [
    {
        key: 'package',
        path: `${PACKAGE_PREFIX_PATH}`,
        title: 'Package',
        translateKey: 'nav.package',
        icon: 'package',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            {
                key: 'collapseMenu.membership',
                path: `${PACKAGE_PREFIX_PATH}/membership`,
                title: 'Membership',
                translateKey: 'nav.collapseMenu.membership',
                icon: 'membership',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const reportsNavigation: NavigationTree[] = [
    {
        key: 'reports',
        path: `${REPORTS_PREFIX_PATH}`,
        title: 'Reports',
        translateKey: 'nav.reports',
        icon: 'reports',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            {
                key: 'collapseMenu.profile',
                path: `${REPORTS_PREFIX_PATH}/profile`,
                title: 'Profile',
                translateKey: 'nav.collapseMenu.profile',
                icon: 'profile',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.activatedeactivate',
                path: `${REPORTS_PREFIX_PATH}/activate-deactivate`,
                title: 'Activate / Deactivate',
                translateKey: 'nav.collapseMenu.activatedeactivate',
                icon: 'activatedeactivate',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.joinings',
                path: `${REPORTS_PREFIX_PATH}/joinings`,
                title: 'Joinings',
                translateKey: 'nav.collapseMenu.joinings',
                icon: 'joinings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.commission',
                path: `${REPORTS_PREFIX_PATH}/commission`,
                title: 'Commission',
                translateKey: 'nav.collapseMenu.commission',
                icon: 'commission',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.totalBonus',
                path: `${REPORTS_PREFIX_PATH}/total-bonus`,
                title: 'Total Bonus',
                translateKey: 'nav.collapseMenu.totalBonus',
                icon: 'totalBonus',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.totalEarners',
                path: `${REPORTS_PREFIX_PATH}/total-earners`,
                title: 'Total Earners',
                translateKey: 'nav.collapseMenu.totalEarners',
                icon: 'totalEarners',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.payout',
                path: `${REPORTS_PREFIX_PATH}/payout`,
                title: 'Payout',
                translateKey: 'nav.collapseMenu.payout',
                icon: 'payout',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.e-pinTransfer',
                path: `${REPORTS_PREFIX_PATH}/e-pin-transfer`,
                title: 'E-pin Transfer',
                translateKey: 'nav.collapseMenu.e-pinTransfer',
                icon: 'e-pinTransfer',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.purchase',
                path: `${REPORTS_PREFIX_PATH}/purchase`,
                title: 'Purchase ',
                translateKey: 'nav.collapseMenu.purchase',
                icon: 'purchase',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.subscriptionreport',
                path: `${REPORTS_PREFIX_PATH}/subscription-report`,
                title: 'Subscription Report',
                translateKey: 'nav.collapseMenu.subscriptionreport',
                icon: 'subscriptionreport',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const toolsNavigation: NavigationTree[] = [
    {
        key: 'tools',
        path: `${TOOLS_PREFIX_PATH}`,
        title: 'Tools',
        translateKey: 'nav.tools',
        icon: 'tools',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            {
                key: 'collapseMenu.uploadedmaterials',
                path: `${TOOLS_PREFIX_PATH}/uploaded-materials`,
                title: 'Uploaded Materials',
                translateKey: 'nav.collapseMenu.uploadedmaterials',
                icon: 'uploadedmaterials',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.news',
                path: `${TOOLS_PREFIX_PATH}/news`,
                title: 'News',
                translateKey: 'nav.collapseMenu.news',
                icon: 'news',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.faq',
                path: `${TOOLS_PREFIX_PATH}/faq`,
                title: 'FAQ ',
                translateKey: 'nav.collapseMenu.faq',
                icon: 'faq',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.promotionaltools',
                path: `${TOOLS_PREFIX_PATH}/promotional-tools`,
                title: 'Promotional Tools ',
                translateKey: 'nav.collapseMenu.promotionaltools',
                icon: 'promotionaltools',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const settingsNavigation: NavigationTree[] = [
    {
        key: 'settings',
        path: `${SETTINGS_PREFIX_PATH}`,
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            {
                key: 'collapseMenu.commissionsettings',
                path: `${SETTINGS_PREFIX_PATH}/commission-settings`,
                title: 'Commission Settings  ',
                translateKey: 'nav.collapseMenu.commissionsettings',
                icon: 'commissionsettings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.advancesettings',
                path: `${SETTINGS_PREFIX_PATH}/advance-settings`,
                title: ' Advance Settings ',
                translateKey: 'nav.collapseMenu.advancesettings',
                icon: 'advancesettings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.companyprofile',
                path: `${SETTINGS_PREFIX_PATH}/company-profile`,
                title: 'Company Profile  ',
                translateKey: 'nav.collapseMenu.companyprofile',
                icon: 'companyprofile',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.contentmanagement',
                path: `${SETTINGS_PREFIX_PATH}/content-management`,
                title: ' Content Management ',
                translateKey: 'nav.collapseMenu.contentmanagement',
                icon: 'contentmanagement',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'collapseMenu.mailcontent',
                path: `${SETTINGS_PREFIX_PATH}/mail-content`,
                title: 'Mail Content  ',
                translateKey: 'nav.collapseMenu.mailcontent',
                icon: 'mailcontent',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'business',
        path: '/business',
        title: 'Business',
        translateKey: 'nav.business',
        icon: 'business',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'e-wallet',
        path: '/e-wallet',
        title: 'E-wallet',
        translateKey: 'nav.e-wallet',
        icon: 'eWallet',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'teams',
        path: '/teams',
        title: 'Teams',
        translateKey: 'nav.teams',
        icon: 'eWallet',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'payout',
        path: '/payout',
        title: 'Payout',
        translateKey: 'nav.payout',
        icon: 'payout',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'candidates',
        path: '/candidates',
        title: 'Candidates',
        translateKey: 'nav.candidates',
        icon: 'candidates',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'franchise-inquiries',
        path: '/franchise-inquiries',
        title: 'Franchise Inquiries',
        translateKey: 'nav.franchise-inquiries',
        icon: 'franchiseinquiries',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'become-consultant',
        path: '/become-consultant',
        title: 'Become Consultant Inquiries',
        translateKey: 'nav.become-consultant',
        icon: 'becomeconsultant',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'contact-us',
        path: '/contact-us',
        title: 'Contact Us Inquiries',
        translateKey: 'nav.contact-us',
        icon: 'contactus',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'franchise-your-business',
        path: '/franchise-your-business',
        title: 'Franchise Your Business',
        translateKey: 'nav.franchise-your-business',
        icon: 'franchiseyourbusiness',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'funding-calculator',
        path: '/funding-calculator',
        title: 'Funding Calculator Inquiries',
        translateKey: 'nav.funding-calculator',
        icon: 'fundingcalculator',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'help-request',
        path: '/help-request',
        title: 'Help Requests',
        translateKey: 'nav.help-request',
        icon: 'helprequest',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    {
        key: 'e-pin',
        path: '/e-pin',
        title: 'E-pin',
        translateKey: 'nav.e-pin',
        icon: 'ePin',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'mailbox',
        path: '/mailbox',
        title: 'Mailbox',
        translateKey: 'nav.mailbox',
        icon: 'mailbox',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    ...networksNavigation,
    ...signupNavigation,
    ...approvalNavigation,
    ...profileManagementNavigation,
    ...packageNavigation,
    ...reportsNavigation,
    ...toolsNavigation,
    ...settingsNavigation,
]

export default navigationConfig
