import {
    // NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'
import {
    DEALSMANAGEMENT_PREFIX_PATH,
    // APPROVAL_PREFIX_PATH,
    INQUIRIES_PREFIX_PATH,
    NETWORKS_PREFIX_PATH,
    // PACKAGE_PREFIX_PATH,
    // PROFILEMANAGEMENT_PREFIX_PATH,
    REPORTS_PREFIX_PATH,
    SETTINGS_PREFIX_PATH,
    SIGNUP_PREFIX_PATH,
    TOOLS_PREFIX_PATH,
    USER_MANAGeMENT_PREFIX_PATH,
    // TOOLS_PREFIX_PATH,
} from '@/constants/route.constant'

const networksNavigation: NavigationTree[] = [
    {
        key: 'networks',
        path: `${NETWORKS_PREFIX_PATH}`,
        title: 'Networks',
        translateKey: 'nav.networks',
        icon: 'networks',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },

        subMenu: [
            {
                key: 'genealogyTree',
                path: `${NETWORKS_PREFIX_PATH}/genealogy-tree`,
                title: 'Genealogy Tree',
                translateKey: 'nav.genealogyTree',
                icon: 'genealogyTree',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // {
            //     key: 'collapseMenu.treeView',
            //     path: `${NETWORKS_PREFIX_PATH}/tree-view`,
            //     title: 'Tree View',
            //     translateKey: 'nav.collapseMenu.treeView',
            //     icon: 'treeView',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            // {
            //     key: 'downlineMembers',
            //     path: `${NETWORKS_PREFIX_PATH}/downline-members`,
            //     title: 'Downline Members',
            //     translateKey: 'nav.downlineMembers',
            //     icon: 'downlineMembers',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
        ],
    },
]

const userManagementNavigation: NavigationTree[] = [
    {
        key: 'userManagement',
        path: '/user-management',
        title: 'User Management',
        translateKey: 'nav.userManagement',
        icon: 'userGroup', // Replace with a relevant icon
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'members',
                path: `${USER_MANAGeMENT_PREFIX_PATH}/members`,
                title: 'Members',
                translateKey: 'nav.members',
                icon: 'members',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'registeruser',
                path: `${USER_MANAGeMENT_PREFIX_PATH}/registeruser`,
                title: 'Register a Ambassador',
                translateKey: 'nav.registeruser',
                icon: 'register',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'consultantregister',
                path: `${USER_MANAGeMENT_PREFIX_PATH}/consultantregister`,
                title: 'Register a Consultant',
                translateKey: 'nav.consultantregister',
                icon: 'register',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inviteusers',
                path: `${USER_MANAGeMENT_PREFIX_PATH}/inviteusers`,
                title: 'Invite Users',
                translateKey: 'nav.inviteusers',
                icon: 'inviteusers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // {
            //     key: 'createTeam',
            //     path: '/create-team',
            //     title: 'Create a Team',
            //     translateKey: 'nav.createTeam',
            //     icon: 'createTeam',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
        ],
    },
]

// const profileManagementNavigation: NavigationTree[] = [
//     {
//         key: 'profileManagement',
//         path: `${PROFILEMANAGEMENT_PREFIX_PATH}`,
//         title: 'Profile Management',
//         translateKey: 'nav.profileManagement',
//         icon: 'profileManagement',
//         type: NAV_ITEM_TYPE_COLLAPSE,
//         authority: [],
//         meta: {
//             horizontalMenu: {
//                 layout: 'columns',
//                 columns: 4,
//             },
//         },
//         subMenu: [
//             {
//                 key: 'collapseMenu.profileview',
//                 path: `${PROFILEMANAGEMENT_PREFIX_PATH}/profile-view`,
//                 title: 'Profile View',
//                 translateKey: 'nav.collapseMenu.profileview',
//                 icon: 'profileview',
//                 type: NAV_ITEM_TYPE_ITEM,
//                 authority: [],
//                 subMenu: [],
//             },
//             // {
//             //     key: 'collapseMenu.memberlist',
//             //     path: `${PROFILEMANAGEMENT_PREFIX_PATH}/member-list`,
//             //     title: 'Member list',
//             //     translateKey: 'nav.collapseMenu.memberlist',
//             //     icon: 'memberlist',
//             //     type: NAV_ITEM_TYPE_ITEM,
//             //     authority: [],
//             //     subMenu: [],
//             // },
//             // {
//             //     key: 'collapseMenu.KYCdetails',
//             //     path: `${PROFILEMANAGEMENT_PREFIX_PATH}/kyc-details`,
//             //     title: 'KYC Details',
//             //     translateKey: 'nav.collapseMenu.KYCdetails',
//             //     icon: 'KYCdetails',
//             //     type: NAV_ITEM_TYPE_ITEM,
//             //     authority: [],
//             //     subMenu: [],
//             // },
//         ],
//     },
// ]

const reportsNavigation: NavigationTree[] = [
    {
        key: 'reports',
        path: `${REPORTS_PREFIX_PATH}`,
        title: 'Reports',
        translateKey: 'nav.reports',
        icon: 'reports',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            // {
            //     key: 'collapseMenu.profile',
            //     path: `${REPORTS_PREFIX_PATH}/profile`,
            //     title: 'Profile',
            //     translateKey: 'nav.collapseMenu.profile',
            //     icon: 'profile',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            // {
            //     key: 'collapseMenu.activatedeactivate',
            //     path: `${REPORTS_PREFIX_PATH}/activate-deactivate`,
            //     title: 'Activate / Deactivate',
            //     translateKey: 'nav.collapseMenu.activatedeactivate',
            //     icon: 'activatedeactivate',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            // {
            //     key: 'collapseMenu.joinings',
            //     path: `${REPORTS_PREFIX_PATH}/joinings`,
            //     title: 'Joinings',
            //     translateKey: 'nav.collapseMenu.joinings',
            //     icon: 'joinings',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            {
                key: 'commission',
                path: `${REPORTS_PREFIX_PATH}/commission`,
                title: 'Commission',
                translateKey: 'nav.commission',
                icon: 'commission',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'totalBonus',
                path: `${REPORTS_PREFIX_PATH}/total-bonus`,
                title: 'Total Bonus',
                translateKey: 'nav.totalBonus',
                icon: 'totalBonus',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'totalEarners',
                path: `${REPORTS_PREFIX_PATH}/total-earners`,
                title: 'Total Earners',
                translateKey: 'nav.totalEarners',
                icon: 'totalEarners',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // {
            //     key: 'collapseMenu.payout',
            //     path: `${REPORTS_PREFIX_PATH}/payout`,
            //     title: 'Payout',
            //     translateKey: 'nav.collapseMenu.payout',
            //     icon: 'payout',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            // {
            //     key: 'collapseMenu.e-pinTransfer',
            //     path: `${REPORTS_PREFIX_PATH}/e-pin-transfer`,
            //     title: 'E-pin Transfer',
            //     translateKey: 'nav.collapseMenu.e-pinTransfer',
            //     icon: 'e-pinTransfer',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            // {
            //     key: 'collapseMenu.purchase',
            //     path: `${REPORTS_PREFIX_PATH}/purchase`,
            //     title: 'Purchase ',
            //     translateKey: 'nav.collapseMenu.purchase',
            //     icon: 'purchase',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            {
                key: 'subscriptionrepor',
                path: `${REPORTS_PREFIX_PATH}/subscription-report`,
                title: 'Subscription Report',
                translateKey: 'nav.subscriptionreport',
                icon: 'subscriptionreport',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const settingsNavigation: NavigationTree[] = [
    {
        key: 'settings',
        path: `${SETTINGS_PREFIX_PATH}`,
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            {
                key: 'collapseMenu.commissionsettings',
                path: `${SETTINGS_PREFIX_PATH}/commission-settings`,
                title: 'Commission Settings  ',
                translateKey: 'nav.collapseMenu.commissionsettings',
                icon: 'commissionsettings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // {
            //     key: 'collapseMenu.advancesettings',
            //     path: `${SETTINGS_PREFIX_PATH}/advance-settings`,
            //     title: ' Advance Settings ',
            //     translateKey: 'nav.collapseMenu.advancesettings',
            //     icon: 'advancesettings',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            {
                key: 'collapseMenu.companyprofile',
                path: `${SETTINGS_PREFIX_PATH}/company-profile`,
                title: 'Company Profile  ',
                translateKey: 'nav.collapseMenu.companyprofile',
                icon: 'companyprofile',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },

            // {
            //     key: 'collapseMenu.mailcontent',
            //     path: `${SETTINGS_PREFIX_PATH}/mail-content`,
            //     title: 'Mail Content  ',
            //     translateKey: 'nav.collapseMenu.mailcontent',
            //     icon: 'mailcontent',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
        ],
    },
]

const inquiriesNavigation: NavigationTree[] = [
    {
        key: 'inquiries',
        path: `${INQUIRIES_PREFIX_PATH}`,
        title: 'Forms Inquiries',
        translateKey: 'nav.inquiries',
        icon: 'inquiries',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            {
                key: 'franchise-inquiries',
                path: `${INQUIRIES_PREFIX_PATH}/franchise-inquiries`,
                title: 'Franchise Inquiries',
                translateKey: 'nav.franchise-inquiries',
                icon: 'franchiseinquiries',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'become-consultant',
                path: `${INQUIRIES_PREFIX_PATH}/become-consultant`,
                title: 'Become Consultant Inquiries',
                translateKey: 'nav.become-consultant',
                icon: 'becomeconsultant',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'contact-us',
                path: `${INQUIRIES_PREFIX_PATH}/contact-us`,
                title: 'Contact Us Inquiries',
                translateKey: 'nav.contact-us',
                icon: 'contactus',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'franchise-your-business',
                path: `${INQUIRIES_PREFIX_PATH}/franchise-your-business`,
                title: 'Franchise Your Business',
                translateKey: 'nav.franchise-your-business',
                icon: 'franchiseyourbusiness',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'funding-calculator',
                path: `${INQUIRIES_PREFIX_PATH}/funding-calculator`,
                title: 'Funding Calculator Inquiries',
                translateKey: 'nav.funding-calculator',
                icon: 'fundingcalculator',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'help-request',
                path: `${INQUIRIES_PREFIX_PATH}/help-request`,
                title: 'Help Requests',
                translateKey: 'nav.help-request',
                icon: 'helprequest',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const toolsNavigation: NavigationTree[] = [
    {
        key: 'tools',
        path: `${TOOLS_PREFIX_PATH}`,
        title: 'Tools',
        translateKey: 'nav.tools',
        icon: 'tools',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        meta: {
            horizontalMenu: {
                layout: 'columns',
                columns: 4,
            },
        },
        subMenu: [
            {
                key: 'e-wallet',
                path: `${TOOLS_PREFIX_PATH}/e-wallet`,
                title: 'E-wallet',
                translateKey: 'nav.e-wallet',
                icon: 'eWallet',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },

            {
                key: 'payout',
                path: `${TOOLS_PREFIX_PATH}/payout`,
                title: 'Payout',
                translateKey: 'nav.payout',
                icon: 'payout',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },

            {
                key: 'mailbox',
                path: `${TOOLS_PREFIX_PATH}/mailbox`,
                title: 'Mailbox',
                translateKey: 'nav.mailbox',
                icon: 'mailbox',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'referralLink',
                path: `${TOOLS_PREFIX_PATH}/referral-link`,
                title: 'All Referral Links',
                translateKey: 'nav.referralLink',
                icon: 'contentmanagement',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const dealsNavigation: NavigationTree[] = [
    {
        key: 'dealsManagement',
        path: `${DEALSMANAGEMENT_PREFIX_PATH}`,
        // path: '/deals-management',
        title: 'Deals Management',
        translateKey: 'nav.dealsManagement',
        icon: 'deals', // Replace with a relevant icon
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'candidates',
                path: `${DEALSMANAGEMENT_PREFIX_PATH}/candidates`,
                // path: '/candidates',
                title: 'Candidates',
                translateKey: 'nav.candidates',
                icon: 'candidates',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'completedDeals',
                path: `${DEALSMANAGEMENT_PREFIX_PATH}/completed-deals`,
                // path: '/completed-deals',
                title: 'Completed Deals', // Updated title
                translateKey: 'nav.completedDeals',
                icon: 'business', // Retain the same icon for now
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teamDeals',
                path: `${DEALSMANAGEMENT_PREFIX_PATH}/team-deals`,
                // path: '/team-deals', // Updated path
                title: "Team's Completed Deals", // Updated title
                translateKey: 'nav.teamDeals',
                icon: 'business', // Retain the same icon for now
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    ...dealsNavigation,
    ...inquiriesNavigation,
    ...networksNavigation,
    ...userManagementNavigation,
    // ...profileManagementNavigation,
    ...reportsNavigation,
    ...toolsNavigation,
]

export default navigationConfig
