import data from '../../../public/files/data.json'

export const countries = [
    { value: '', label: 'Choose Your Country' },

    { value: 'Albania', label: 'Albania' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Armenia', label: 'Armenia' },
    { value: 'Austria', label: 'Austria' },
    { value: 'Australia', label: 'Australia' },
    { value: 'Azerbaijan', label: 'Azerbaijan' },
    { value: 'Bahrain', label: 'Bahrain' },
    { value: 'Bangladesh', label: 'Bangladesh' },
    { value: 'Belgium', label: 'Belgium' },
    { value: 'Bolivia', label: 'Bolivia' },
    { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
    { value: 'Bulgaria', label: 'Bulgaria' },
    { value: 'Cameroon', label: 'Cameroon' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Chile', label: 'Chile' },

    { value: 'ChinaTaiwan', label: 'China (Taiwan)' },
    { value: 'Colombia', label: 'Colombia' },
    { value: 'Republic of the Congo', label: 'Republic of the Congo' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Croatia', label: 'Croatia' },
    { value: 'Czechia', label: 'Czechia' },
    { value: 'Denmark', label: 'Denmark' },
    { value: 'Ecuador', label: 'Ecuador' },
    { value: 'Egypt', label: 'Egypt' },
    { value: 'Estonia', label: 'Estonia' },
    { value: 'Ethiopia', label: 'Ethiopia' },
    { value: 'Finland', label: 'Finland' },
    { value: 'France', label: 'France' },
    { value: 'Georgia', label: 'Georgia' },
    { value: 'Germany', label: 'Germany' },
    { value: 'Grenada', label: 'Grenada' },
    { value: 'Honduras', label: 'Honduras' },

    { value: 'Ireland', label: 'Ireland' },
    { value: 'Israel', label: 'Israel' },
    { value: 'Italy', label: 'Italy' },
    { value: 'Jamaica', label: 'Jamaica' },
    { value: 'Japan', label: 'Japan' },
    { value: 'Jordan', label: 'Jordan' },
    { value: 'Kazakhstan', label: 'Kazakhstan' },
    { value: 'Kosovo', label: 'Kosovo' },
    { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
    { value: 'Latvia', label: 'Latvia' },
    { value: 'Liberia', label: 'Liberia' },
    { value: 'Lithuania', label: 'Lithuania' },
    { value: 'Luxembourg', label: 'Luxembourg' },
    { value: 'Mexico', label: 'Mexico' },
    { value: 'Moldova', label: 'Moldova' },
    { value: 'Mongolia', label: 'Mongolia' },
    { value: 'Montenegro', label: 'Montenegro' },
    { value: 'Morocco', label: 'Morocco' },
    { value: 'Netherlands', label: 'Netherlands' },
    { value: 'New Zealand', label: 'New Zealand' },

    { value: 'Norway', label: 'Norway' },
    { value: 'Oman', label: 'Oman' },
    { value: 'Pakistan', label: 'Pakistan' },
    { value: 'Panama', label: 'Panama' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Philippines', label: 'Philippines' },
    { value: 'Poland', label: 'Poland' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Romania', label: 'Romania' },
    { value: 'Senegal', label: 'Senegal' },
    { value: 'Serbia', label: 'Serbia' },
    { value: 'Singapore', label: 'Singapore' },
    { value: 'Slovakia', label: 'Slovakia' },
    { value: 'Slovenia', label: 'Slovenia' },
    { value: 'South Korea', label: 'South Korea' },
    { value: 'Spain', label: 'Spain' },
    { value: 'Sri Lanka', label: 'Sri Lanka' },
    { value: 'Suriname', label: 'Suriname' },
    { value: 'Sweden', label: 'Sweden' },
    { value: 'Switzerland', label: 'Switzerland' },
    { value: 'Thailand', label: 'Thailand' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
    { value: 'Tunisia', label: 'Tunisia' },
    { value: 'Turkey', label: 'Turkey' },
    { value: 'Ukraine', label: 'Ukraine' },
    { value: 'UnitedKingdom', label: 'United Kingdom' },
    { value: 'Yugoslavia', label: 'Yugoslavia' },
]

export const steps = [
    'New Deal',
    'Initial Call Attempt',
    'Connected',
    'Spoton/Candidate Research',
    'Research & Prep Presentation',
    'Present Franchise Review',
    'Intro to Zor',
    'Franchise Due Diligence',
    'Validation - FSO',
    'Discovery Day/Award - FSO',
    'Closed Won',
    'Closed Lost',
    'On Hold',
]

export const states = [
    { value: 'Alabama', text: 'Alabama' },
    { value: 'Alberta', text: 'Alberta' },
    { value: 'Alaska', text: 'Alaska' },
    { value: 'Arizona', text: 'Arizona' },
    { value: 'Arkansas', text: 'Arkansas' },
    { value: 'British Columbia', text: 'British Columbia' },
    { value: 'California', text: 'California' },
    { value: 'Colorado', text: 'Colorado' },
    { value: 'Connecticut', text: 'Connecticut' },
    { value: 'Delaware', text: 'Delaware' },
    { value: 'District Of Columbia', text: 'District Of Columbia' },
    { value: 'Florida', text: 'Florida' },
    { value: 'Georgia', text: 'Georgia' },
    { value: 'Hawaii', text: 'Hawaii' },
    { value: 'Idaho', text: 'Idaho' },
    { value: 'Illinois', text: 'Illinois' },
    { value: 'Indiana', text: 'Indiana' },
    { value: 'Iowa', text: 'Iowa' },
    { value: 'Kansas', text: 'Kansas' },
    { value: 'Kentucky', text: 'Kentucky' },
    { value: 'Louisiana', text: 'Louisiana' },
    { value: 'Maine', text: 'Maine' },
    { value: 'Manitoba', text: 'Manitoba' },
    { value: 'Maryland', text: 'Maryland' },
    { value: 'Massachusetts', text: 'Massachusetts' },
    { value: 'Michigan', text: 'Michigan' },
    { value: 'Minnesota', text: 'Minnesota' },
    { value: 'Mississippi', text: 'Mississippi' },
    { value: 'Missouri', text: 'Missouri' },
    { value: 'Montana', text: 'Montana' },
    { value: 'Nebraska', text: 'Nebraska' },
    { value: 'Nevada', text: 'Nevada' },
    { value: 'New Brunswick', text: 'New Brunswick' },
    { value: 'New Hampshire', text: 'New Hampshire' },
    { value: 'New Jersey', text: 'New Jersey' },
    { value: 'New Mexico', text: 'New Mexico' },
    { value: 'New York', text: 'New York' },
    { value: 'Newfoundland and Labrador', text: 'Newfoundland and Labrador' },
    { value: 'North Carolina', text: 'North Carolina' },
    { value: 'North Dakota', text: 'North Dakota' },

    { value: 'Northwest Territories', text: 'Northwest Territories' },
    { value: 'Nova Scotia', text: 'Nova Scotia' },
    { value: 'Nunavut', text: 'Nunavut' },
    { value: 'Ohio', text: 'Ohio' },
    { value: 'Oklahoma', text: 'Oklahoma' },
    { value: 'Ontario', text: 'Ontario' },
    { value: 'Oregon', text: 'Oregon' },
    { value: 'Pennsylvania', text: 'Pennsylvania' },
    { value: 'Prince Edward Island', text: 'Prince Edward Island' },
    { value: 'Quebec', text: 'Quebec' },
    { value: 'Rhode Island', text: 'Rhode Island' },
    { value: 'South Carolina', text: 'South Carolina' },
    { value: 'South Dakota', text: 'South Dakota' },
    { value: 'Saskatchewan', text: 'Saskatchewan' },
    { value: 'Tennessee', text: 'Tennessee' },
    { value: 'Texas', text: 'Texas' },
    { value: 'Utah', text: 'Utah' },
    { value: 'Vermont', text: 'Vermont' },
    { value: 'Virginia', text: 'Virginia' },
    { value: 'Washington', text: 'Washington' },
    { value: 'West Virginia', text: 'West Virginia' },
    { value: 'Wisconsin', text: 'Wisconsin' },
    { value: 'Wyoming', text: 'Wyoming' },
    { value: 'Yukon Territory', text: 'Yukon Territory' },
    { value: 'International', text: 'International' },
]

export const getCitiesOfState = (stateCode) => {
    if (stateCode) {
        return data[stateCode] || []
    } else {
        return []
    }
}

export const hearAbout = [
    { name: 'Select an option', text: '' },
    { name: 'Seach Engine', text: 'Seach Engine' },
    { name: 'Billboard', text: 'Billboard' },
    { name: 'Social(Facebook, Instagram, LinkedIn, etc.)', text: 'Social' },
    { name: 'Youtube', text: 'Youtube' },
    { name: 'TV', text: 'TV' },
    { name: 'Radio(AM/FM/XM)', text: 'Radio(AM/FM/XM)' },
    { name: 'In The Mail', text: 'In The Mail' },
    { name: 'Podcast', text: 'Podcast' },
    {
        name: 'Streaming Audio (Pandora, Spotify, etc.)',
        text: 'Streaming Audio (Pandora, Spotify, etc.)',
    },
    { name: 'Other', text: 'Other' },
]
