import {
    PiMicrosoftTeamsLogoDuotone,
    PiCalculatorDuotone,
    PiFolderSimplePlusDuotone,
    PiBuildingsDuotone,
    PiPhoneIncomingDuotone,
    PiUsersFourDuotone,
    PiUserSquareDuotone,
    PiBasketDuotone,
    PiHouseLineDuotone,
    PiArrowsInDuotone,
    PiNetworkDuotone,
    PiUserListDuotone,
    // PiJoystickDuotone,
    PiWalletDuotone,
    PiCurrencyCircleDollarDuotone,
    // PiListNumbersDuotone,
    PiUserCircleCheckDuotone,
    // PiPackageDuotone,
    PiBookOpenDuotone,
    PiToolboxDuotone,
    PiDotsThreeCircleDuotone,
    PiMailboxDuotone,
    PiBuildingOfficeDuotone,
    PiNetworkXDuotone,
    PiTreeDuotone,
    PiTreeViewDuotone,
    PiUserCheckDuotone,
    PiUsersThreeDuotone,
    PiCheckCircleDuotone,
    PiIdentificationBadgeDuotone,
    PiListChecksDuotone,
    PiArticleDuotone,
    PiPlusCircleDuotone,
    PiUserDuotone,
    PiRepeatDuotone,
    PiMoneyWavyDuotone,
    PiInvoiceDuotone,
    PiTipJarDuotone,
    PiRepeatOnceDuotone,
    PiSubtitlesDuotone,
    PiNewspaperClippingDuotone,
    PiArrowSquareDownDuotone,
    PiChatCenteredTextDuotone,
    PiQuestionMarkDuotone,
    PiUserListFill,
} from 'react-icons/pi'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    teams: <PiMicrosoftTeamsLogoDuotone />,
    userGroup: <PiMicrosoftTeamsLogoDuotone />,
    inquiries: <PiUserListDuotone />,
    home: <PiHouseLineDuotone />,
    networks: <PiNetworkDuotone />,
    signup: <PiUserListDuotone />,
    // approval: <PiJoystickDuotone />,
    business: <PiBuildingOfficeDuotone />,
    candidates: <PiUsersFourDuotone />,
    deals: <PiUsersFourDuotone />,
    franchiseinquiries: <PiBasketDuotone />,
    becomeconsultant: <PiUserSquareDuotone />,
    contactus: <PiPhoneIncomingDuotone />,
    franchiseyourbusiness: <PiBuildingsDuotone />,
    fundingcalculator: <PiCalculatorDuotone />,
    helprequest: <PiFolderSimplePlusDuotone />,
    eWallet: <PiWalletDuotone />,
    consultants: <PiUserListFill />,
    payout: <PiCurrencyCircleDollarDuotone />,
    // ePin: <PiListNumbersDuotone />,
    profileManagement: <PiUserCircleCheckDuotone />,
    // package: <PiPackageDuotone />,
    reports: <PiBookOpenDuotone />,
    tools: <PiToolboxDuotone />,
    settings: <PiDotsThreeCircleDuotone />,
    mailbox: <PiMailboxDuotone />,
    genealogyTree: <PiNetworkXDuotone />,
    treeView: <PiTreeDuotone />,
    downlineMembers: <PiTreeViewDuotone />,
    register: <PiUserCheckDuotone />,
    bulkRegister: <PiUsersThreeDuotone />,
    registerationApproval: <PiCheckCircleDuotone />,
    profileview: <PiIdentificationBadgeDuotone />,
    memberlist: <PiListChecksDuotone />,
    KYCdetails: <PiArticleDuotone />,
    membership: <PiPlusCircleDuotone />,
    profile: <PiUserDuotone />,
    activatedeactivate: <PiRepeatDuotone />,
    joinings: <PiArrowsInDuotone />,
    commission: <PiMoneyWavyDuotone />,
    totalBonus: <PiInvoiceDuotone />,
    totalEarners: <PiTipJarDuotone />,
    ePinTransfer: <PiRepeatOnceDuotone />,
    purchase: <PiSubtitlesDuotone />,
    subscriptionreport: <PiNewspaperClippingDuotone />,
    uploadedmaterials: <PiArrowSquareDownDuotone />,
    news: <PiChatCenteredTextDuotone />,
    faq: <PiQuestionMarkDuotone />,
}

export default navigationIcon
