export const ROOT = '/'

export const NETWORKS_PREFIX_PATH = '/networks'
export const SETTINGS_PREFIX_PATH = '/settings'
export const INQUIRIES_PREFIX_PATH = '/inquiries'
export const USER_MANAGeMENT_PREFIX_PATH = '/user-management'
export const SIGNUP_PREFIX_PATH = '/signup'
export const APPROVAL_PREFIX_PATH = '/approval'
export const TOOLS_PREFIX_PATH = '/tools'
export const PACKAGE_PREFIX_PATH = '/ourPackages'
export const REPORTS_PREFIX_PATH = '/reports'
export const PROFILEMANAGEMENT_PREFIX_PATH = '/profile-management'
export const DEALSMANAGEMENT_PREFIX_PATH = '/deals-management'
